# Generated by Django 5.1.6 on 2025-02-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('lb', 'per lb'), ('each', 'each')], default='each', max_length=10),
        ),
    ]
